# Generated by Django 5.1.3 on 2025-02-25 02:38

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Contract",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("contract_no", models.CharField(max_length=100)),
                ("title", models.CharField(max_length=255)),
                ("company_name", models.CharField(max_length=255)),
                ("location", models.CharField(max_length=255)),
                ("contract_advert", models.FileField(upload_to="contracts/")),
                ("company_profile", models.FileField(upload_to="contracts/")),
                ("contract_agreement", models.FileField(upload_to="contracts/")),
                (
                    "variations",
                    models.FileField(blank=True, null=True, upload_to="contracts/"),
                ),
                ("applications", models.FileField(upload_to="contracts/")),
                ("certificate_no_objection", models.FileField(upload_to="contracts/")),
                ("award_certificate", models.FileField(upload_to="contracts/")),
                ("completion_certificate", models.FileField(upload_to="contracts/")),
                ("drawing", models.FileField(upload_to="contracts/")),
                ("certificate_valuation", models.FileField(upload_to="contracts/")),
                ("approvals", models.FileField(upload_to="contracts/")),
            ],
        ),
        migrations.CreateModel(
            name="Property",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("property_no", models.CharField(max_length=50)),
                ("coordinate", models.CharField(max_length=100)),
                ("location", models.CharField(max_length=100)),
                ("cost", models.DecimalField(decimal_places=2, max_digits=15)),
                (
                    "property_type",
                    models.CharField(
                        choices=[
                            ("Residential", "Residential"),
                            ("Commercial", "Commercial"),
                            ("Industrial", "Industrial"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "passport",
                    models.ImageField(
                        blank=True, null=True, upload_to="property_passports/"
                    ),
                ),
            ],
        ),
    ]
